/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ClinicRole;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business;
import model.WorkQueue.RequirementMsgs;
import model.WorkQueue.WorkRequest;
import model.organization.ClinicOrganization;
import model.vaccinemgnt.Vaccine;

/**
 *
 * @author wenwen
 */
public class WorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Business business;
    /**
     * Creates new form WorkRequestJPanel
     */
    public WorkRequestJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.jPanel1=userProcessContainer;
        this.business=business.theInstance();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVaccTrpe = new javax.swing.JLabel();
        blAmount = new javax.swing.JLabel();
        lblMsgs = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVaccType = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtMsgs = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        lblVaccTrpe.setText("Vaccine Type:");

        blAmount.setText("Amount:");

        lblMsgs.setText("Message:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("New Work Request");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVaccTrpe)
                            .addComponent(blAmount)
                            .addComponent(lblMsgs))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVaccType)
                            .addComponent(txtAmount)
                            .addComponent(txtMsgs, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(btnCreate)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel4)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaccTrpe)
                    .addComponent(txtVaccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blAmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMsgs)
                    .addComponent(txtMsgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnCreate)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        

            RequirementMsgs rm = new RequirementMsgs();

            rm.setVaccine(txtVaccType.getText());
            rm.setMessage(txtMsgs.getText());
            String amountText = txtAmount.getText();
            int amount = Integer.parseInt(amountText);
            rm.setAmount(amount);

            ClinicOrganization clinicOrg = business.getOrganizationDirectory().getClinicOrganization(); 
            RequirementMsgs createMsgsRequest = clinicOrg.getMsgsDirectory().createMsgsRequest(rm.getVaccine(), rm.getAmount(), rm.getMessage(), "confirmed");

            JOptionPane.showMessageDialog(null, "Msgs added successfully. Will be forwarded to the next receiver");
            txtVaccType.setText("");
            txtMsgs.setText("");
            txtAmount.setText("");

       
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blAmount;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnCreateUser1;
    private javax.swing.JButton btnCreateUser2;
    private javax.swing.JButton btnCreateUser3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMsgs;
    private javax.swing.JLabel lblVaccTrpe;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtMsgs;
    private javax.swing.JTextField txtVaccType;
    // End of variables declaration//GEN-END:variables
}
